on:
  push:
    tags:
      - '*'

name: Upload release

jobs:
  upload_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        run: echo $RELEASE_VERSION > release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}